openapi: 3.0.0
info:
  title: afsuam-mx-af00X-sa-safre-hello-world
  version: 1.0.0
  description: |
    API System de Hello World conectada a la base de datos "administracion"
    para mostrar un ejemplo básico aplicando buenas prácticas de desarrollo.
  contact:
    name: Equipo de API
    email: desarrollo@suramexico.com
servers:
  - url: http://localhost:8080
    description: Entorno local

paths:
  /v1/hello/world:
    $ref: "paths/v1_hello_world.yaml"
